Clean up warnings in tests
iridl/python-maprooms pull request #377
Opened 2023-09-12 20:25 UTC by aaron-kaplan

2023-09-13 19:04 UTC, remicousin requested changes

2023-09-13 19:04 UTC, remicousin commented on enacts/wat_bal/agronomy.py
> +    modelizing crop rooting depth. :math:`\\rh\\_crop` can be further adjusted as a function of
o has droppped so
rho
not
rh

2023-09-14 20:40 UTC, aaron-kaplan commented
What, it's not sufficient to silence the warnings, you also want the documentation to render correctly? So demanding :-/

I'm embarassed to ask, but how do I generate the documentation HTML?

2023-09-20 13:34 UTC, remicousin commented
> What, it's not sufficient to silence the warnings, you also want the documentation to render correctly? So demanding :-/
> 
> I'm embarassed to ask, but how do I generate the documentation HTML?

make html

it's in the [README](https://github.com/iridl/python-maprooms/tree/master/enacts)

2023-09-20 13:34 UTC, remicousin approved these changes

2023-09-20 13:40 UTC, merged