Icon for KMD
iridl/python-maprooms pull request #382
Opened 2023-10-11 14:44 UTC by remicousin

Is missing and thus their Python Maprooms return a broken image where it's meant to be.

2023-10-11 15:17 UTC, aaron-kaplan approved these changes

2023-10-11 15:18 UTC, aaron-kaplan requested changes
Wait, no, shouldn't this be in python_maprooms_kmd?

2023-10-11 15:23 UTC, aaron-kaplan commented
I see that indeed we're putting all the logos  in the container. That sucks because it means I have to build and publish a new version of the container each time we set up a new partner. We should instead
- Add the icon file to python_maproom_kmd
- Modify the python_maproom_kmd Dockerfile to COPY the icon file into the container to a directory where it will be picked up by dash/flask. I don't know offhand what location that is. @xchourio can you work on this?

2024-02-21 14:15 UTC, remicousin commented
So I think we are discarding this PR right? since you set up so that can be added to the country config repo.

2024-02-21 16:17 UTC, closed without merging